<?php
/**
 * This file is generated by WP Starter package, and contains base configuration of the WordPress.
 *
 * All the configuration constants used by WordPress are set via environment variables.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 *
 * A sample .env file (.env.example) should be placed in the root of your project, rename it to .env
 * and edit it according to your needs.
 */

/**
 * Composer autoload.
 */
require_once realpath(__DIR__.'/wp-content/vendor'.'/autoload.php');

/**
 * Configuration constants.
 *
 * Use environment variables to set WordPress constants.
 * Mandatory settings:
 * - DB_NAME
 * - DB_USER
 * - DB_PASSWORD
 *
 * @var array $env All the variables stored in environment variables
 */
$env = WCM\WPStarter\Helpers::settings(__DIR__, '.env');
array_walk($env, function ($value, $name) {
    switch ($name) {
        case 'DB_TABLE_PREFIX':
            $GLOBALS['table_prefix'] = preg_replace('#[^\w]#', '', $value);
            break;
        default:
            defined($name) or define($name, $value);
            break;
    }
});

/**
 * Set optional database settings if not already set
 */
defined('DB_HOST')    or define('DB_HOST',    'localhost');
defined('DB_CHARSET') or define('DB_CHARSET', 'utf8');
defined('DB_COLLATE') or define('DB_COLLATE', '');

/**
 * Set WordPress Database Table prefix if not already set.
 *
 * @global string $table_prefix
 */
if (! isset($table_prefix) || empty($table_prefix)) {
    $table_prefix = 'wp_';
}

/**
 * Set unique authentication keys if not already set via environment variables.
 */
defined('AUTH_KEY')         or define('AUTH_KEY',         '46`9n!=V=c8^ht[iAd].:%j084V_P*UsONOK>b:S4q9|5}:B<qWM=&IDwnwCa1ME');
defined('SECURE_AUTH_KEY')  or define('SECURE_AUTH_KEY',  'e]9w1hXo!9jg3Z7s*)w/N_#312*Ch4Z0^2jVo]fIz(p1kH;/%Ub^wTC&OZWx0_7Q');
defined('LOGGED_IN_KEY')    or define('LOGGED_IN_KEY',    'Q7$.Kx,}uK-o->A?9B&UbvT$]Ft3mag+Ncyw0#{ekM i&fY{BShi+`t4c3{z/6*&');
defined('NONCE_KEY')        or define('NONCE_KEY',        'w?-XT1+qCbn# Tt<Gd3d_Q5zQ2L9,9^{pq(<H%NY-lE5nRO~P<p`_Zzmk5=yXqS[');
defined('AUTH_SALT')        or define('AUTH_SALT',        '$2&dXy:M$Xa/ D$YgHEYIwE,fG-!Fr1V^@jVz>9a>n45VHq^e1$N?^~}`E06(3xI');
defined('SECURE_AUTH_SALT') or define('SECURE_AUTH_SALT', 'Co~Rb,+BoS(irZ[,[tQ=a%YcO|Q{?%DT*co|1X8DxOD(rnDL,D%5OyFTjQ^yEBTl');
defined('LOGGED_IN_SALT')   or define('LOGGED_IN_SALT',   'uF&ES@peaJ1j6 ho`u&gbUYvAZ%dA0g0<*qg/MT!tq+Vz(ZMI0Rju0*]v2X-huk:');
defined('NONCE_SALT')       or define('NONCE_SALT',       'T,HIH+`<fk^ s$)vZpvQH89@AO}0;kqy&@^qPI$gaiiR8ngiko9J7*E5ibh?z-!z');

/**
 * Environment-aware settings. Be creative, but avoid to set sensitive settings here.
 */
$environment = getenv('WORDPRESS_ENV');
switch ($environment) {

    case 'development':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        defined('SAVEQUERIES')      or define('SAVEQUERIES',      true);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     true);
        break;

    case 'staging':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     true);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     true);
        break;

    case 'production':
    default:
        defined('WP_DEBUG')         or define('WP_DEBUG',         false);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     false);
        break;
}

/**
 * Fix HTTPS behind load balancers.
 *
 * @link https://core.trac.wordpress.org/ticket/31288
 * @link https://github.com/wecodemore/wpstarter/issues/7
 */
if (
    isset($_SERVER['HTTP_X_FORWARDED_PROTO'])
	&& 'https' === strtolower($_SERVER['HTTP_X_FORWARDED_PROTO'])
) {
	$_SERVER[ 'HTTPS' ] = 'on';
}

/**
 * Set WordPress paths and urls if not set via environment variables.
 */
if (! defined('WP_HOME')) {
    $server = filter_input_array(INPUT_SERVER, array(
        'HTTPS'       => FILTER_SANITIZE_STRING,
        'SERVER_PORT' => FILTER_SANITIZE_NUMBER_INT,
        'SERVER_NAME' => FILTER_SANITIZE_URL,
    ));
    $secure = in_array((string) $server['HTTPS'], array('on', '1'), true);
    $scheme = $secure ? 'https://' : 'http://';
    $name   = $server['SERVER_NAME'] ? : 'localhost';
    define('WP_HOME', $scheme.$name);
}
defined('ABSPATH')        or define('ABSPATH',        realpath(__DIR__.'/wp'));
defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(__DIR__.'/wp-content'));
defined('WP_SITEURL')     or define('WP_SITEURL',     rtrim(WP_HOME, '/').'/wp');
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/').'/wp-content');

/**
 * Clean up.
 */
unset($env, $environment, $server, $secure, $scheme, $name);

/**
 * Allows to load MU plugins in subfolders.
 */
WCM\WPStarter\Helpers::addHook(
    'muplugins_loaded',
    new WCM\WPStarter\MuLoader\MuLoader(),
    PHP_INT_MAX,
    0
);

/**
 * Register default themes inside WordPress package wp-content folder.
 */
WCM\WPStarter\Helpers::addHook('plugins_loaded', function () {
    WCM\WPStarter\Helpers::loadThemeFolder(true);
}, 0);

/**
 * Sets up WordPress vars and included files.
 */
require_once ABSPATH.DIRECTORY_SEPARATOR.'wp-settings.php';
