<?php
/**
 * This file is generated by WP Starter package, and contains base configuration of the WordPress.
 *
 * All the configuration constants used by WordPress are set via environment variables.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 *
 * A sample .env file (.env.example) should be placed in the root of your project, rename it to .env
 * and edit it according to your needs.
 */

/**
 * Composer autoload.
 */
require_once realpath(dirname(__DIR__).'/htdocs/content/vendor'.'/autoload.php');

/**
 * Configuration constants.
 *
 * Use environment variables to set WordPress constants.
 * Mandatory settings:
 * - DB_NAME
 * - DB_USER
 * - DB_PASSWORD
 *
 * @var array $env All the variables stored in environment variables
 */
$env = WCM\WPStarter\Helpers::settings(dirname(__DIR__), '.env');
array_walk($env, function ($value, $name) {
    switch ($name) {
        case 'DB_TABLE_PREFIX':
            $GLOBALS['table_prefix'] = preg_replace('#[^\w]#', '', $value);
            break;
        default:
            defined($name) or define($name, $value);
            break;
    }
});

/**
 * Set optional database settings if not already set
 */
defined('DB_HOST')    or define('DB_HOST',    'localhost');
defined('DB_CHARSET') or define('DB_CHARSET', 'utf8');
defined('DB_COLLATE') or define('DB_COLLATE', '');

/**
 * Set WordPress Database Table prefix if not already set.
 *
 * @global string $table_prefix
 */
if (! isset($table_prefix) || empty($table_prefix)) {
    $table_prefix = 'wp_';
}

/**
 * Set unique authentication keys if not already set via environment variables.
 */
defined('AUTH_KEY')         or define('AUTH_KEY',         'j;/aijX_d:5{Hp~X|>hyZPH*oWkvJ1`<A?.aS;by#+1+Z0c^{Jfd+k/lQ8|ojpo`');
defined('SECURE_AUTH_KEY')  or define('SECURE_AUTH_KEY',  'xsax:yA(/ZeRu&xW.|=E()AS>^u{ fL&;&d}16s)G-3[v_7O&|/ka#Vyu3XmfFd0');
defined('LOGGED_IN_KEY')    or define('LOGGED_IN_KEY',    'OcI;I 2sxJ.6. Q-2P1P%NhWgR4,`2a[cy@Sk3Z4#FMr{@ZBEXPA}hNNV: U1@1I');
defined('NONCE_KEY')        or define('NONCE_KEY',        '<,bKt*^@&MSoLr.@bjqc1yd0i_H+?S&dLBiu2tA9iayiHn0q7nE<gcrLS!r5d],P');
defined('AUTH_SALT')        or define('AUTH_SALT',        '^].rgPCIW1Dw^qGwYK|MppM<~UYqDb,Ms{G_Ynb9(e# `oanfDDA!3v=D~ByiX?[');
defined('SECURE_AUTH_SALT') or define('SECURE_AUTH_SALT', '?.JQ]3qt5V]Zz ,*HMywU:Av4NxQJ,Q-&D+D+,b[s)z3* YW>X(f$S2s$pRyg?$<');
defined('LOGGED_IN_SALT')   or define('LOGGED_IN_SALT',   'aM<Y,z8ZP|Gg)P<&!1)J3oZSaN2P.i5&m)&_Xq8k(zOzMW^BJ5P2Vd*=EdHn%,in');
defined('NONCE_SALT')       or define('NONCE_SALT',       '#O,$U/_Em<|M$hco*1T%bJg{*&bMXpi/xmr1?}ct>JB+RUN:*@GYimWeWOsg!Q8+');

/**
 * Environment-aware settings. Be creative, but avoid to set sensitive settings here.
 */
$environment = getenv('WORDPRESS_ENV');
switch ($environment) {

    case 'development':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        defined('SAVEQUERIES')      or define('SAVEQUERIES',      true);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     true);
        break;

    case 'staging':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     true);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     true);
        break;

    case 'production':
    default:
        defined('WP_DEBUG')         or define('WP_DEBUG',         false);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     false);
        break;
}

/**
 * Fix HTTPS behind load balancers.
 *
 * @link https://core.trac.wordpress.org/ticket/31288
 * @link https://github.com/wecodemore/wpstarter/issues/7
 */
if (
    isset($_SERVER['HTTP_X_FORWARDED_PROTO'])
	&& 'https' === strtolower($_SERVER['HTTP_X_FORWARDED_PROTO'])
) {
	$_SERVER[ 'HTTPS' ] = 'on';
}

/**
 * Set WordPress paths and urls if not set via environment variables.
 */
if (! defined('WP_HOME')) {
    $server = filter_input_array(INPUT_SERVER, array(
        'HTTPS'       => FILTER_SANITIZE_STRING,
        'SERVER_PORT' => FILTER_SANITIZE_NUMBER_INT,
        'SERVER_NAME' => FILTER_SANITIZE_URL,
    ));
    $secure = in_array((string) $server['HTTPS'], array('on', '1'), true);
    $scheme = $secure ? 'https://' : 'http://';
    $name   = $server['SERVER_NAME'] ? : 'localhost';
    define('WP_HOME', $scheme.$name);
}
defined('ABSPATH')        or define('ABSPATH',        realpath(dirname(__DIR__).'/public/wp'));
defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(dirname(__DIR__).'/public/content'));
defined('WP_SITEURL')     or define('WP_SITEURL',     rtrim(WP_HOME, '/').'/wp');
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/').'/content');

/**
 * Clean up.
 */
unset($env, $environment, $server, $secure, $scheme, $name);

/**
 * Allows to load MU plugins in subfolders.
 */
WCM\WPStarter\Helpers::addHook(
    'muplugins_loaded',
    new WCM\WPStarter\MuLoader\MuLoader(),
    PHP_INT_MAX,
    0
);

/**
 * Register default themes inside WordPress package wp-content folder.
 */
WCM\WPStarter\Helpers::addHook('plugins_loaded', function () {
    WCM\WPStarter\Helpers::loadThemeFolder(true);
}, 0);

/**
 * Sets up WordPress vars and included files.
 */
require_once ABSPATH.DIRECTORY_SEPARATOR.'wp-settings.php';
